server:
    port: 8080




##database_01
#db1.driverClassName = com.mysql.jdbc.Driver
#db1.dbUrl=jdbc:mysql://192.16.6.96:13306/weilai_finance?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#db1.username=root
#db1.password=123456
#
##database_02
#db2.driverClassName = com.mysql.jdbc.Driver
#db2.dbUrl=jdbc:mysql://192.16.6.96:13306/weilai_assets?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#db2.username=root
#db2.password=123456